### PR TITLE
Clarified instructions and added examples.

### PR DESCRIPTION
**Pull request by player-03**

### CODE REVIEW

**Comment by shoebox** [comment]
Thanks, need to update those for the new version ;)

**Comment by player-03** [comment]
What needs to be added? Anything besides `JNI_DEFAULT_PACKAGE`?

**Comment by shoebox** [comment]
I will add some instructions about how to run the test units, how work the default method response, how to use the abstracts...

**Comment by player-03** [comment]
I'm still linking people to this library because it works so well, but it really needs a clear readme. Can you pull this request?

**Comment by player-03** [comment]
Closing because I'm pushing too many unrelated commits.

**Pull request closed without merging**
